### ISSUE TITLE
[Request] Config file to allow certain interactions

### ISSUE THREAD

**Issue by Zero-Starlight** [PhantomGamers/Valheim-PreventAccidentalInteraction#1]
Hi, love the mod, it really helps avoid annoyance when trying to open up chests in our cubby setup. I was wondering if you wouldn't, as the title suggests, be able to add some options to interact with certain objects without needing to crouch. Specifically AnyPortal requires the player to interact with the portal to select a destination, and it creates a situation where I'd personally prefer not to have to crouch each time I want to select a destination. If such an option already exists, I have not been able to find it yet. Thanks!

**Comment by PhantomGamers** [comment]
I can do this I'm just not positive how to do it cleanly lol, I will look into it but in the mean time you can use the first released version which should do what you want with the only side effect being that interactions with the guardian power stones at spawn will require crouching, but I imagine that would be better for you.

**Comment by PhantomGamers** [comment]
Done in bb3c0faed2589c5f4da87a9c9353f94b568af1fa
