### ISSUE TITLE
Feature request: hide interaction options until interaction is allowed

### ISSUE THREAD

**Issue by torarnv** [PhantomGamers/Valheim-PreventAccidentalInteraction#3]
One QOL addition, that I dont know if would be possible, would be to hide the "[E] Interact" hover text in the UI until the item can be interacted with. Do you think that's possible?

**Comment by torarnv** [comment]
Perhaps you can hook into the part that only shows the interaction when you're close enough, and change it to a very small or zero distance as the required distance, as a way to hide and prevent the interaction?

(which would be a nice mod on its own. some of the items are a bit awkard to interact with, so a larger lookat-radius would be nice).

**Comment by PhantomGamers** [comment]
Good suggestion, I will implement this!

**Comment by PhantomGamers** [comment]
One potential issue with implementing this would be that it would also apply to portals where being able to see the text is important to making sure you're going in the right portal.

Basically I don't know how I would explicitly just remove the button prompts as the entire thing is just a single text string, so I think the only thing I can do is hide the entire thing. I mean I could hardcode the prompt text per-interaction but that wouldn't be great for compatibility... hmm

I will implement this anyway, but it'll be an option that is disabled by default in the config, unless there is a better solution to this that I am missing.

**Comment by PhantomGamers** [comment]
Done in 1.0.6 baf9d89bd8776ede23c5659e6320e3f9dea52921

**Comment by torarnv** [comment]
Wow, thank you so much!! Works exactly as I had hoped!
