### ISSUE TITLE
Feature request: Custom key to enable interaction

### ISSUE THREAD

**Issue by torarnv** [PhantomGamers/Valheim-PreventAccidentalInteraction#4]
Crouch mode as a default is fine, but crouch means I'm walking slowly, and also can't crouch when holding hammer. It would be nice if a custom key could be configured to toggle the interaction, by holding e.g. shift, or some other key. Thanks!!

**Comment by PhantomGamers** [comment]
I will work on this

**Comment by PhantomGamers** [comment]
Done in 1.0.6 baf9d89bd8776ede23c5659e6320e3f9dea52921

**Comment by torarnv** [comment]
Works perfectly, thank you very much!
